services:
  - type: web
    name: srushti-os
    env: node
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm install -g serve && serve -s dist
    autoDeploy: false
